version: "3.8"

services:
  app:
    build:
      context: ./backend   # шлях до папки з NestJS
    container_name: nest-backend
    env_file:
      - .env
    volumes:
         - ./backend:/app
         - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=owu.linkpc.net
      - DB_PORT=3306
      - DB_USER=crmaplications
      - DB_PASSWORD=ElenaStr
      - DB_NAME=crmaplications
    command: >
      sh -c "npm run migration:run && npm run start"
    restart: always

  frontend:
      build:
        context: ./frontend   # React
      container_name: react-frontend
      ports:
        - "80:80"
      depends_on:
        - app
      environment:
        - REACT_APP_API_URL=http://app:3000
#  web:
#    image: nginx:alpine
#    container_name: nginx-web
#    ports:
#      - "80:80"
#    depends_on:
#      - app
#    volumes:
#      - ./client:/usr/share/nginx/html
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf